version: '3.8'
services:
  album:
    build: ./album
    restart: always
    ports:
      - $LOCAL_PORT:$DOCKER_PORT
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
          "server.port" : "$DOCKER_PORT"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true